name: Build Pibooth Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y debootstrap dosfstools mtools qemu-user-static binfmt-support libarchive-tools parted python3-yaml rsync xz-utils genimage mmdebstrap bdebstrap crudini pv dctrl-tools

    - name: Checkout rpi-image-gen
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/rpi-image-gen
        path: rpi-image-gen

    - name: Make apt-key executable
      run: chmod +x device/hooks/setup.d/01-apt-keys.sh

    - name: Copy build definitions into rpi-image-gen
      run: |
        cp -r config profile meta device image rpi-image-gen/

    - name: Build image
      run: |
        cd rpi-image-gen
        IG_USE_PODMAN=0 ./build.sh ../config/image.ini pibooth
    
    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: pibooth-os-image
        path: rpi-image-gen/workspace/images/pibooth-os.img*
